version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sharepointoscar/cars-api:v2
    ports:
      - '1337:1337'
    environment:
      - NODE_ENV=development
      - PORT=1337
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
      - ENABLE_ELASTICSEARCH=false
      - DISABLE_SAILS_SEED=false
    depends_on:
      - database
    links:
      - database
  database:
    image: mongo:3.2.12
    ports:
      - 27017:27017
    volumes:
      - /Users/sharepointoscar/Documents:/var/lib/mongodb
